### ISSUE TITLE
The example file does not generate the same pdf as in the result folder in GitHub

### ISSUE THREAD

**Issue by miwamasa** [gireeshkbogu/AnomalyDetect#1]
Hi, thanks for sharing your interesting work.

I have tried with the AHYIJDV sample file:
  python hrosad_offline.py  --myphd_id AHYIJDV --heart_rate AHYIJDV_hr.csv --steps AHYIJDV_steps.csv -outliers_fraction 0.1  --random_seed 10 

the result pdf file in the Github does not match the result I got.

It seems you have not updated your results on GitHub after your latest modification of hrosad_offline.py  

 https://github.com/gireeshkbogu/AnomalyDetect/commit/37fa5759842c4539f657ebcc160052a8da296895

The pity thing is the result, which is most updated one, does not seem sexy!!!
Best Regards

**Comment by gireeshkbogu** [comment]
Thank you for your interest in my work. I updated files with the latest scripts. Please keep in mind that I might update these scripts in the future and please let me know if you have any other issues.
