### ISSUE TITLE
The argument of some of the class HROSAD_offline' methods are not used

### ISSUE THREAD

**Issue by miwamasa** [gireeshkbogu/AnomalyDetect#2]
The argument of some of the class HROSAD_offline' methods are not used
The code still works because the data/dataframes are treated as global variable.
It looks like as if you have firstly started with plain python script like jupyter notebook.

For example

def standardization(self, seasonality_corrected_data):

  seasonality_corrected_data is not used in the body.

def anomaly_detection(self, standardized_data):

  standardized_data is not used in the body

**Comment by gireeshkbogu** [comment]
Seasonality correction was not applied in the original paper. It was deliberately not used.
